### ISSUE TITLE
silent fail when creating an APIProduct with non DNS-1123 compliant name

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo-portal-issues#20] opened 2020-12-11 16:08 UTC
When creating an APIProduct, with a non-compliant name:

![image](https://user-images.githubusercontent.com/9626829/101926003-e1a83400-3bd2-11eb-8031-e543da6f5f02.png)

![image](https://user-images.githubusercontent.com/9626829/101925910-bae9fd80-3bd2-11eb-9080-c43e228dc84e.png)

This silently fails.

In the developer tools, the call to CreateAPIProduct returns this error msg:
`grpc-message: APIProduct.devportal.solo.io "Pets API" is invalid: metadata.name: Invalid value: "Pets API": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`

Could we show an error message in the UI?
BTW, even if I correct the name, I cannot click again on the "Create API Product" button.

**Comment by estahn** [comment] 2020-12-16 08:28
It's a duplicate of #18

**Comment by marcogschmidt** [comment] 2021-01-08 16:09
This has been fixed and will be released with version `0.5.1`.

**Closed by marcogschmidt** 2021-01-08 16:09 UTC
Labels: Type: Bug
